pipeline {
    agent any

    stages {
        stage('Checkout') {
            steps {
                git branch: 'main',
                    credentialsId: 'github-creds',
                    url: 'https://github.com/<your-username>/alx-backend-python.git'
            }
        }

        stage('Install dependencies') {
            steps {
                sh '''
                    pip3 install --upgrade pip
                    pip3 install -r messaging_app/requirements.txt
                '''
            }
        }

        stage('Run Tests') {
            steps {
                sh '''
                    pytest messaging_app/tests --junitxml=report.xml --cov=messaging_app
                '''
            }
            post {
                always {
                    junit 'report.xml'
                }
            }
        }
    }
}

